version: '3.9'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: gunicorn --bind 0.0.0.0:5000 ACEest_Fitness:app

  sonar:
    image: sonarsource/sonarqube-community:10.1-community
    ports:
      - '9000:9000'
    environment:
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions

volumes:
  sonar_data:
  sonar_extensions:
