sonar.projectKey=ACEestFitness
sonar.projectName=ACEest Fitness Application
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/**,k8s/**,versions/**,README.md,REPORT.md
sonar.python.coverage.reportPaths=coverage.xml
